name: ${PROJECT_NAME}

services:
  php:
    build:
      context: ./services/php/${PHP_VERSION}
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-php:${REDIS_VERSION}
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ${APP_ROOT}:/var/www
      - ${STORAGE_DATA}:/mnt/storage
      - ${PHP_CUSTOM_CONF}:/tmp/php-custom.ini
    environment:
      PHP_CUSTOM_CONF_ENABLED: ${PHP_CUSTOM_CONF_ENABLED}
    networks:
      - app-network

  nginx:
    build:
      context: ./services/nginx/${NGINX_VERSION}
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-nginx:${NGINX_VERSION}
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - "${NGINX_PUBLIC_PORT}:80"
    volumes:
      - ${APP_ROOT}:/var/www
      - ${STORAGE_DATA}:/mnt/storage
      - ${NGINX_CUSTOM_CONF}:/tmp/nginx-custom.conf
    environment:
      APP_PUBLIC: ${APP_PUBLIC}
      NGINX_CUSTOM_CONF_ENABLED: ${NGINX_CUSTOM_CONF_ENABLED}
    depends_on:
      - php
    networks:
      - app-network

  mariadb:
    build:
      context: ./services/mariadb/${MARIADB_VERSION}
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-mariadb:${REDIS_VERSION}
    container_name: ${PROJECT_NAME}-mariadb
    ports:
      - "${MARIADB_PUBLIC_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_USER_PASSWORD}
    volumes:
      - ${MARIADB_DATA}:/var/lib/mysql
    networks:
      - app-network

  redis:
    build:
      context: ./services/redis/${REDIS_VERSION}
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-redis:${REDIS_VERSION}
    container_name: ${PROJECT_NAME}-redis
    ports:
      - "${REDIS_PUBLIC_PORT}:6379"
    volumes:
      - ${REDIS_DATA}:/data
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge