name: ${PROJECT_NAME}

services:
  php:
    build:
      context: ./services/php/${PHP_VERSION}
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-php-${PHP_VERSION}
    volumes:
      - ${APP_PATH}:/var/www/html
    environment:
      PHP_INI_MEMORY_LIMIT: 256M
      PHP_INI_UPLOAD_MAX_FILESIZE: 10M
      PHP_INI_POST_MAX_SIZE: 10M
    networks:
      - app-network

  nginx:
    build:
      context: ./services/nginx/${NGINX_VERSION}
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-nginx:${NGINX_VERSION}
    container_name: ${PROJECT_NAME}-nginx-${NGINX_VERSION}
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ${APP_PATH}:/var/www/html
      - ./services/nginx/${NGINX_VERSION}/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
    environment:
      PUBLIC_PATH: ${PUBLIC_PATH}
    depends_on:
      - php
    networks:
      - app-network

  mariadb:
    build:
      context: ./services/mariadb/${MARIADB_VERSION}
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-mariadb-${MARIADB_VERSION}
    ports:
      - "${MARIADB_HOST_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - app-network

  redis:
    build:
      context: ./services/redis/${REDIS_VERSION}
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-redis:${REDIS_VERSION}
    container_name: ${PROJECT_NAME}-redis-${REDIS_VERSION}
    ports:
      - "6379:6379"
    volumes:
      - ./data/cache:/data
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge