FROM redis:latest

# Você pode adicionar comandos aqui se precisar de alguma configuração extra.
# Por exemplo, para copiar um arquivo de configuração redis.conf:
# COPY ./redis.conf /usr/local/etc/redis/redis.conf
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]